"""
Generated by Claude 3/24/26
Prompt: "Write an OpenCV program in Python that will do color detection on a Raspberry Pi 4 version B"
Color Detection for Raspberry Pi 4 Model B
===========================================
Detects colors in real-time using OpenCV and HSV color space.
Supports Pi Camera (via picamera2) or a USB webcam.

Requirements:
    pip install opencv-python numpy
    sudo apt install python3-picamera2   # for Pi Camera (optional)

Usage:
    python color_detection_pi.py               # uses USB webcam (default)
    python color_detection_pi.py --picam       # uses Raspberry Pi Camera
    python color_detection_pi.py --color red   # detect only red at startup
"""

import cv2
import numpy as np
import argparse
import sys

# ──────────────────────────────────────────────
# HSV Color Ranges
# Hue: 0-179, Saturation: 0-255, Value: 0-255
# ──────────────────────────────────────────────
COLOR_RANGES = {
    "red": [
        (np.array([0,   120,  70]),  np.array([10,  255, 255])),
        (np.array([170, 120,  70]),  np.array([180, 255, 255])),   # red wraps around 180
    ],
    "orange": [
        (np.array([10,  120,  70]),  np.array([25,  255, 255])),
    ],
    "yellow": [
        (np.array([25,  100,  70]),  np.array([35,  255, 255])),
    ],
    "green": [
        (np.array([36,  100,  70]),  np.array([86,  255, 255])),
    ],
    "blue": [
        (np.array([94,  100,  70]),  np.array([126, 255, 255])),
    ],
    "purple": [
        (np.array([127, 50,   70]),  np.array([155, 255, 255])),
    ],
    "white": [
        (np.array([0,   0,   200]),  np.array([180,  30, 255])),
    ],
    "black": [
        (np.array([0,   0,    0]),   np.array([180,  255, 50])),
    ],
}

# BGR display colors for bounding boxes / labels
DISPLAY_COLORS = {
    "red":    (0,   0,   220),
    "orange": (0,   140, 255),
    "yellow": (0,   220, 220),
    "green":  (0,   200, 60),
    "blue":   (220, 80,  0),
    "purple": (180, 0,   180),
    "white":  (230, 230, 230),
    "black":  (60,  60,  60),
}

MIN_CONTOUR_AREA = 1500   # ignore tiny blobs (px²)
FRAME_WIDTH      = 640
FRAME_HEIGHT     = 480


# ──────────────────────────────────────────────
# Camera helpers
# ──────────────────────────────────────────────

def open_usb_camera(index: int = 0):
    cap = cv2.VideoCapture(index)
    if not cap.isOpened():
        sys.exit(f"[ERROR] Could not open USB camera at index {index}.")
    cap.set(cv2.CAP_PROP_FRAME_WIDTH,  FRAME_WIDTH)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, FRAME_HEIGHT)
    cap.set(cv2.CAP_PROP_FPS, 30)
    print(f"[INFO] USB camera opened (index={index}).")
    return cap


def open_pi_camera():
    """Returns a picamera2 instance configured for OpenCV (BGR numpy arrays)."""
    try:
        from picamera2 import Picamera2  # type: ignore
    except ImportError:
        sys.exit(
            "[ERROR] picamera2 not found.\n"
            "Install with:  sudo apt install python3-picamera2\n"
            "Or use a USB webcam (omit --picam)."
        )
    picam = Picamera2()
    config = picam.create_preview_configuration(
        main={"size": (FRAME_WIDTH, FRAME_HEIGHT), "format": "BGR888"}
    )
    picam.configure(config)
    picam.start()
    print("[INFO] Pi Camera opened via picamera2.")
    return picam


def read_frame(source, use_picam: bool) -> np.ndarray:
    if use_picam:
        return source.capture_array()
    else:
        ret, frame = source.read()
        if not ret:
            sys.exit("[ERROR] Failed to grab frame from USB camera.")
        return frame


# ──────────────────────────────────────────────
# Core detection
# ──────────────────────────────────────────────

def build_mask(hsv: np.ndarray, color_name: str) -> np.ndarray:
    """Return a combined binary mask for all HSV ranges of a color."""
    mask = np.zeros(hsv.shape[:2], dtype=np.uint8)
    for (lo, hi) in COLOR_RANGES[color_name]:
        mask |= cv2.inRange(hsv, lo, hi)
    # Morphological clean-up: remove noise, fill holes
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN,  kernel, iterations=2)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=2)
    return mask


def detect_and_annotate(frame: np.ndarray, active_colors: list) -> np.ndarray:
    """
    For each active color, find contours in the HSV mask and draw
    bounding boxes + labels on the original frame.
    """
    hsv    = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    output = frame.copy()

    for color_name in active_colors:
        mask      = build_mask(hsv, color_name)
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        bgr       = DISPLAY_COLORS.get(color_name, (255, 255, 255))

        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area < MIN_CONTOUR_AREA:
                continue

            x, y, w, h = cv2.boundingRect(cnt)
            cx = x + w // 2
            cy = y + h // 2

            # Bounding box
            cv2.rectangle(output, (x, y), (x + w, y + h), bgr, 2)

            # Label background
            label    = f"{color_name}  {int(area)}px"
            (tw, th), baseline = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.55, 1)
            cv2.rectangle(output, (x, y - th - baseline - 4), (x + tw + 4, y), bgr, -1)

            # Label text (black for readability on bright boxes)
            txt_color = (0, 0, 0) if color_name not in ("black", "blue", "purple") else (255, 255, 255)
            cv2.putText(output, label, (x + 2, y - baseline - 2),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, txt_color, 1, cv2.LINE_AA)

            # Center dot
            cv2.circle(output, (cx, cy), 5, bgr, -1)

    return output


# ──────────────────────────────────────────────
# HUD / UI helpers
# ──────────────────────────────────────────────

def draw_hud(frame: np.ndarray, active_colors: list, all_colors: list) -> np.ndarray:
    """Draw a semi-transparent HUD showing active / available colors and key bindings."""
    overlay = frame.copy()
    h, w    = frame.shape[:2]

    # Bottom bar background
    cv2.rectangle(overlay, (0, h - 34), (w, h), (30, 30, 30), -1)
    cv2.addWeighted(overlay, 0.6, frame, 0.4, 0, frame)

    instructions = "Keys:  [1-8] toggle color   [a] all   [n] none   [q] quit"
    cv2.putText(frame, instructions, (8, h - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.45, (200, 200, 200), 1, cv2.LINE_AA)

    # Color pills at top
    pill_x = 8
    for i, name in enumerate(all_colors):
        active = name in active_colors
        bgr    = DISPLAY_COLORS[name] if active else (70, 70, 70)
        label  = f"{i+1}:{name}"
        (tw, _), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.42, 1)
        cv2.rectangle(frame, (pill_x, 6), (pill_x + tw + 8, 24), bgr, -1 if active else 1)
        txt_c = (0, 0, 0) if (active and name not in ("black", "blue", "purple")) else (220, 220, 220)
        cv2.putText(frame, label, (pill_x + 4, 20),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.42, txt_c, 1, cv2.LINE_AA)
        pill_x += tw + 14

    return frame


# ──────────────────────────────────────────────
# Main loop
# ──────────────────────────────────────────────

def run(use_picam: bool = False, initial_color: str = None):
    all_colors    = list(COLOR_RANGES.keys())
    active_colors = [initial_color] if initial_color else list(all_colors)

    source = open_pi_camera() if use_picam else open_usb_camera()

    print("\n[INFO] Starting color detection. Press 'q' to quit.\n")
    print("  Keys 1-8 toggle individual colors:")
    for i, name in enumerate(all_colors):
        print(f"    {i+1}  →  {name}")
    print("  a  →  enable all colors")
    print("  n  →  disable all colors\n")

    while True:
        frame  = read_frame(source, use_picam)
        output = detect_and_annotate(frame, active_colors)
        output = draw_hud(output, active_colors, all_colors)

        cv2.imshow("Color Detection  —  Pi 4B", output)

        key = cv2.waitKey(1) & 0xFF

        if key == ord('q'):
            break
        elif key == ord('a'):
            active_colors = list(all_colors)
        elif key == ord('n'):
            active_colors = []
        elif ord('1') <= key <= ord('8'):
            idx  = key - ord('1')
            name = all_colors[idx]
            if name in active_colors:
                active_colors.remove(name)
                print(f"[INFO] Disabled: {name}")
            else:
                active_colors.append(name)
                print(f"[INFO] Enabled:  {name}")

    # Clean up
    cv2.destroyAllWindows()
    if use_picam:
        source.stop()
    else:
        source.release()
    print("[INFO] Done.")


# ──────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Real-time color detection on Raspberry Pi 4B.")
    parser.add_argument("--picam",  action="store_true",
                        help="Use the Raspberry Pi Camera instead of a USB webcam.")
    parser.add_argument("--color",  type=str, default=None,
                        choices=list(COLOR_RANGES.keys()),
                        help="Detect only this color at startup (default: all).")
    args = parser.parse_args()

    run(use_picam=args.picam, initial_color=args.color)
